### ISSUE TITLE
I can't do simple call

### ISSUE THREAD

**Issue by Callmedachang** [straightdave/arion#11]
Thanks for this nice tool:
    but  I have a puzzle，
![image](https://user-images.githubusercontent.com/16498541/57123219-a8330400-6db3-11e9-8225-754480faeba2.png)
then I use :
![image](https://user-images.githubusercontent.com/16498541/57123247-b7b24d00-6db3-11e9-9fd6-72307b1f739d.png)
I am sure that the service is running and the simple call is also successful.
Can you help me ? Thanks

**Comment by Callmedachang** [comment]
Looks like it can't connected  to my local GRPC service endpoint, is there I  forget something to do?

**Comment by Callmedachang** [comment]
sorry for my stupid question.Thanks again

**Comment by straightdave** [comment]
Yeah. Sorry for the typical 'TL;DR' readme documentation.
If '-h' is not specified, it would call '0.0.0.0:8087' and obviously you may not host your service on your local machine at port 8087.

**Comment by straightdave** [comment]
And that error message is from gRPC library and means timeout while trying to setup connection.
