### ISSUE TITLE
use of internal package vendor/google.golang.org/grpc/internal not allowed

### ISSUE THREAD

**Issue by zhwentao** [straightdave/arion#8]
## output
2018/11/14 14:48:26 generating new pb file: temp-listsvr-694865551/pb.go
2018/11/14 14:48:26 generating meta source file: temp-listsvr-694865551/meta.go
2018/11/14 14:48:26 creating new source file: temp-listsvr-694865551/main.go
2018/11/14 14:48:26 creating new source file: temp-listsvr-694865551/static.go
2018/11/14 14:48:26 change dir to /Users/zhaowentao/go/src/github.com/straightdave/arion/temp-listsvr-694865551
2018/11/14 14:48:26 Analyzing dependencies ...
2018/11/14 14:48:26 Install dependencies ...
stderr ../../../../google.golang.org/grpc/clientconn.go:39:2: use of internal package vendor/google.golang.org/grpc/internal not allowed
error exit status 1
complete
2018/11/14 14:48:27 Build ...
stderr # github.com/straightdave/trunks/lib
stderr ../../trunks/lib/burn.go:287:10: c.Invoke undefined (type *grpc.ClientConn has no field or method Invoke)
stderr ../../trunks/lib/burn.go:287:60: undefined: grpc.CallContentSubtype
stderr ../../trunks/lib/burn.go:291:10: c.Invoke undefined (type *grpc.ClientConn has no field or method Invoke)
error exit status 2

## env
gopath ~/go/
repro path ~/go/src/github.com/straightdave/arion

exec ./arion -src path ~/go/src/github.com/straightdave/arion

**Comment by straightdave** [comment]
The errors is `vendor`-related and I still think it's mysterious. Please try following approaches:
1. Use Arion out of your `$GOPATH` (say, a new folder named `~/arion_files/`).
2. Update Arion by executing `go get -u github.com/straightdave/arion` and repeat 1.
3. Make sure the $GOPATH is set well (`echo $GOPATH`) before using Arion.

**Comment by straightdave** [comment]
Update:
When we meet the conflict caused by `_vendor_` (say, the `pb` used to generate has one imported package that prefers to some in a project or a folder where `_vendor_` folders exist.)
In this case, the solution is temporarily rename the `vendor` to another name say `_vendor` before executing arion generating.
